//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventr.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingEnt
    {
        public BookingEnt()
        {
            this.BookingAdditionalServices = new HashSet<BookingAdditionalServiceEnt>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid VenueId { get; set; }
        public System.Guid EventCategoryId { get; set; }
        public System.DateTime BookingTimeFrom { get; set; }
        public System.DateTime BookingTimeTo { get; set; }
        public int Pax { get; set; }
        public string EventBriteID { get; set; }
    
        public virtual UserEnt User { get; set; }
        public virtual EventCategoryEnt EventCategory { get; set; }
        public virtual VenueEnt Venue { get; set; }
        public virtual ICollection<BookingAdditionalServiceEnt> BookingAdditionalServices { get; set; }
    }
}
