//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventr.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediumEnt
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> VenueId { get; set; }
        public Nullable<System.Guid> AdditionalServiceId { get; set; }
        public string mediaFileName { get; set; }
        public string filePath { get; set; }
    
        public virtual AdditionalServiceEnt AdditionalService { get; set; }
        public virtual VenueEnt Venue { get; set; }
    }
}
