//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventr.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVenueEnt
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid VenueId { get; set; }
    
        public virtual UserEnt User { get; set; }
        public virtual VenueEnt Venue { get; set; }
    }
}
