//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventrAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingAdditionalServiceEnt
    {
        public Nullable<System.Guid> BookingID { get; set; }
        public Nullable<System.Guid> AdditionalServiceID { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual AdditionalServiceEnt AdditionalService { get; set; }
        public virtual BookingEnt Booking { get; set; }
    }
}
