//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventrAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCategoryEnt
    {
        public EventCategoryEnt()
        {
            this.Bookings = new HashSet<BookingEnt>();
            this.ServiceTypeEventCategories = new HashSet<ServiceTypeEventCategoryEnt>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BookingEnt> Bookings { get; set; }
        public virtual ICollection<ServiceTypeEventCategoryEnt> ServiceTypeEventCategories { get; set; }
    }
}
