//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventrAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTypeEventCategoryEnt
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ServiceTypeId { get; set; }
        public Nullable<System.Guid> EventCategoryId { get; set; }
    }
}
